Singleton
PKR511/Battle-Tank pull request #1
Opened 2020-04-10 08:01 UTC by PKR511

Singleton Demo

2020-04-11 16:27 UTC, mayankgrover requested changes

2020-04-11 16:27 UTC, mayankgrover commented on Assets/Scripts/Battle_Tank/Tanks/TankController.cs
> +			TankService.Instance.FireBullet (tankView);
vector3

2020-04-11 16:27 UTC, mayankgrover commented on Assets/Scripts/Battle_Tank/Tanks/TankView.cs
> +				myBody.MovePosition (transform.position + transform.forward * (moveVertical *0.1f));
tankController.tankModel.speed;

2020-04-28 06:46 UTC, closed without merging

2020-04-28 06:46 UTC, PKR511 commented
done